---
name: Lint Code Base
on: push

jobs:
    build:
        name: Lint Code Base
        runs-on: ubuntu-latest

        steps:
            ##########################
            # Checkout the code base #
            ##########################
            - name: Checkout Code
              uses: actions/checkout@v2

            ################################
            # Run Linter against code base #
            ################################
            - name: Lint Code Base
              uses: docker://github/super-linter:v2.2.0
              env:
                  LINTER_RULES_PATH: /
                  VALIDATE_ALL_CODEBASE: false
                  VALIDATE_JAVASCRIPT_ES: true
                  VALIDATE_TYPESCRIPT_ES: true
                  VALIDATE_CSS: true
                  VALIDATE_JSON: true
                  VALIDATE_YAML: true
                  VALIDATE_XML: true
                  VALIDATE_MD: true
                  VALIDATE_BASH: true
                  VALIDATE_PYTHON: true
